version: '3.9'

services:
  db:
    image: postgres:14.10
    restart: always
    container_name: postgresql_blog
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Asegúrate de que este volumen apunte al directorio correcto en tu sistema local
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: my_database
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin

volumes:
  postgres_data:
